![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

1.4.3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [3]:
pd.Series()

C:\Users\DELL\AppData\Local\Temp\ipykernel_7184\2031691219.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()


Series([], dtype: float64)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [8]:
# your code goes here
X = [i for i in range(5)]
Y = pd.Series(X)
print('X Datatype: {}, Y Datatype: {}'.format(type(X),type(Y)))

X Datatype: <class 'list'>, Y Datatype: <class 'pandas.core.series.Series'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [12]:
# your code goes here
X = pd.Series()
X.name = 'My letters'
X

C:\Users\DELL\AppData\Local\Temp\ipykernel_7184\39237083.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  X = pd.Series()


Series([], Name: My letters, dtype: float64)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values


In [23]:
# your code goes here
letters  = ['A','B','C','D','E']
X = pd.Series(letters)
X.values

array(['A', 'B', 'C', 'D', 'E'], dtype=object)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series


In [39]:
# your code goes here
nums = ['letter '+ str(i) for i in range(1,6)]
letters  = ['A','B','C','D','E']
X = pd.Series(letters, index = nums)
X

letter 1    A
letter 2    B
letter 3    C
letter 4    D
letter 5    E
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element


In [34]:
# your code goes here
X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element


In [36]:
# your code goes here
X[-1]

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements


In [37]:
# your code goes here
X[1:-1]

letter 1    B
letter 2    C
letter 3    D
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position


In [38]:
# your code goes here
X[::-1]

letter 4    E
letter 3    D
letter 2    C
letter 1    B
letter 0    A
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements


In [40]:
# your code goes here
X[[0,-1]]

letter 1    A
letter 5    E
dtype: object

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float


In [55]:
# your code goes here
index_list=['first','second','third','forth','fifth']
X = pd.Series([x for x in range(1,6)],index = index)
X = X.astype("float16")
X

first     1.0
second    2.0
third     3.0
forth     4.0
fifth     5.0
dtype: float16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [60]:
# your code goes here
X = X[::-1]
X

fifth     5.0
forth     4.0
third     3.0
second    2.0
first     1.0
dtype: float16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series


In [64]:
# your code goes here
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10


In [68]:
# your code goes here
X = pd.Series([x for x in range(1,11)])
X[4] = 10
X.values

array([ 1,  2,  3,  4, 10,  6,  7,  8,  9, 10], dtype=int64)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0


In [70]:
# your code goes here
X = pd.Series([x for x in range(1,16)])
X[1:-1] = 10
X.values

array([ 1, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 15],
      dtype=int64)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element


In [76]:
# your code goes here
X = pd.Series([x for x in range(-4,16)])
print(X.values)
X = X + 5
print(X.values)

[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements


In [77]:
# your code goes here
X = pd.Series([x for x in range(-10,10)])
mask = X < 0
mask

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements


In [78]:
# your code goes here
X = pd.Series([x for x in range(-10,10)])
mask = X < 0
X[mask]

0   -10
1    -9
2    -8
3    -7
4    -6
5    -5
6    -4
7    -3
8    -2
9    -1
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5


In [81]:
# your code goes here
X = pd.Series([x for x in range(0,11)])
mask = X > 5
X[mask]

6      6
7      7
8      8
9      9
10    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [83]:
# your code goes here
X = pd.Series([x for x in range(0,11)])
mask = X > X.mean()
X[mask]

6      6
7      7
8      8
9      9
10    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10


In [85]:
# your code goes here
X = pd.Series([x for x in range(0,11)])
mask = (X == 2) | (X==10)
X[mask]

2      2
10    10
dtype: int64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

### Given the X pandas Series, return True if none of its elements is zero

In [90]:
# your code goes here
X = pd.Series([x for x in range(-10,11)])
X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero


In [91]:
# your code goes here
X = pd.Series([x for x in range(-10,11)])
X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements


In [93]:
# your code goes here
X = pd.Series([x for x in range(-10,11)])
X.sum()

0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [94]:
# your code goes here
X = pd.Series([x for x in range(-10,11)])
X.mean()

0.0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [95]:
# your code goes here
X = pd.Series([x for x in range(-10,11)])
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)