![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.1


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#np.array([0] * 10)
np.zeros(10)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [ ]:
# your code goes here
np.arange(10,50)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
# your code goes here
np.ones([2,2], dtype = np.int)

C:\Users\DELL\AppData\Local\Temp\ipykernel_11556\2277411856.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype = np.int)


array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [5]:
# your code goes here
np.ones([3,2], dtype = np.float)

C:\Users\DELL\AppData\Local\Temp\ipykernel_11556\3720441133.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype = np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [10]:
# your code goes here
X = np.arange(4, dtype = int)
np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [11]:
# your code goes here
np.zeros_like(X)

array([0, 0, 0, 0])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [17]:
# your code goes here
np.ones([4,4]) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [18]:
# your code goes here
np.ones_like(X) * 7

array([7, 7, 7, 7])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [19]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [21]:
# your code goes here
np.random.randint(10, size=3)

array([4, 7, 7])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [22]:
# your code goes here
np.random.randn(3,3,3)

array([[[ 0.09339748,  0.10193304,  0.00732735],
        [-1.26112358,  2.61871588, -1.3365434 ],
        [-0.13272775, -0.64252588,  1.46871702]],

       [[ 1.01271791, -1.54287563,  0.17916847],
        [ 1.22355269,  1.66750596, -0.79212309],
        [ 0.84598152,  0.50365212,  0.6404146 ]],

       [[-1.78036703, -1.80136759, -0.56911612],
        [ 0.65793025,  0.72780926,  0.90297157],
        [-0.08881399, -0.8755966 ,  1.10932654]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [26]:
# your code goes here
X = [1,2,3,4]
Y = np.array(X)
type(Y)

numpy.ndarray

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [28]:
# your code goes here
X = np.arange(10)
Y = X.copy()
print(X == Y)

[ True  True  True  True  True  True  True  True  True  True]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [31]:
# your code goes here
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [32]:
# your code goes here
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [40]:
# your code goes here
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [49]:
# your code goes here
#np.arange(9).reshape(3,3)
a = np.random.randint(8,size=3)
b = np.vstack([a,a,a])
b.shape

(3, 3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [69]:
# your code goes here
Z = np.arange(20,dtype=int)
print("%d bytes" % (Z.size * Z.itemsize))

80 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [71]:
# your code goes here
X[0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [72]:
# your code goes here
X[-1]

10

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [74]:
# your code goes here
X[0:3]

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [75]:
# your code goes here
X[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [76]:
# your code goes here
X[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [79]:
X = np.array(['A','B','C','D','E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [3]:
# your code goes here
X = np.arange(9).reshape(3,3)
X[0]

array([0, 1, 2])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [93]:
# your code goes here
X[-1]

array([6, 7, 8])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [94]:
# your code goes here
X[0][0]

0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [95]:
# your code goes here
X[-1][-1]

8

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [99]:
# your code goes here
X[1:-1, 1:-1]

array([[4]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [118]:
# your code goes here
print(X)
X[0:2,0:2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1],
       [3, 4]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [8]:
# your code goes here
print(X)
X[-2:, -2:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[4, 5],
       [7, 8]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [14]:
# your code goes here
X = np.arange(10,dtype = int)
print(X.dtype)
X = X.astype('float')
print(X.dtype)

int32
float64


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [17]:
# your code goes here
X = np.arange(1,11)
X[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [20]:
# your code goes here
X = np.random.randint(1,11,size=10)
X
np.sort(X)

array([ 3,  3,  3,  4,  5,  7,  7,  8,  8, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [23]:
# your code goes here
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [12]:
# your code goes here
X = np.arange(3,8) * 10
#X[2] = 40
X[np.where(X==50)] =  40
X

array([30, 40, 40, 60, 70])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [15]:
# your code goes here
X = np.random.randint(25,size=(3,3))
X[-1] = 1
X

array([[ 3,  0,  5],
       [21,  3,  6],
       [ 1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [16]:
# your code goes here
X = np.random.randint(25,size=(3,3))
X[-1] = np.zeros(3)
X

array([[ 1, 10,  6],
       [23,  5, 24],
       [ 0,  0,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [17]:
# your code goes here
X += 5
X

array([[ 6, 15, 11],
       [28, 10, 29],
       [ 5,  5,  5]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [26]:
# your code goes here
X = np.random.randint(-10,5,size = 10)
mask = X < 0
mask

array([ True, False,  True,  True,  True, False, False, False,  True,
        True])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [27]:
# your code goes here
X = np.random.randint(-10,5,size = 10)
mask = X < 0
X[mask]

array([ -8,  -5,  -7, -10,  -6, -10,  -6])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [30]:
# your code goes here
X = np.random.randint(15,size = 10)
mask = X > 5
X[mask]

array([ 6, 11, 10,  7,  7,  9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [33]:
# your code goes here
X = np.random.randint(15,size = 10)
mask = X > X.mean()
X[mask],X.mean()

(array([14,  9, 11,  9, 14, 14]), 8.4)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [76]:
# your code goes here
X = np.random.randint(15,size = 10)
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [96]:
# your code goes here
X = np.random.randint(-5,15,size = 10)
mask = X.any()
X,mask

(array([ 1,  0, -3, -3, 14, 12,  7, 10, -5, 10]), True)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [140]:
X = np.random.randint(-5,15,size = 10)
mask = X.any()
X,mask

(array([11,  3,  7, -2, -5, 13,  9,  2,  2,  3]), True)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [101]:
# your code goes here
X = np.random.randint(20,size = 10)
X.sum()

101

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [116]:
# your code goes here
X = np.random.randint(20,size = 10)
X.mean(dtype = int)

9

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [136]:
# your code goes here
X = np.random.randint(20,size = (3,3))
print(X)
print("sum =",X.sum(axis = 0))

[[ 0 16 15]
 [14  4 15]
 [17 13  7]]
sum = [31 33 37]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [138]:
# your code goes here
X = np.random.randint(20,size = (3,3))
print(X)
print("mean =",X.mean(axis = 1,dtype = int))

[[ 3  7  1]
 [ 2 12 10]
 [18  2 15]]
mean = [ 3  8 11]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [139]:
# your code goes here
X = np.random.randint(20,size = 20)
X.max()

18

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)